
# Non Stationary Time-series

*This section explicitly identifies how to check for non stationarity and how to deal with it*

*Hence:*

1. Unit roots
2. Spurious Regression
3. Cointegration

**Literature**

+ HW: Judgmental Forecasting and Forecast Adjustments (Combining forecasts)
+ HW: Managing the Forecast Process
+ Discussion on Diebold-Mariano test: http://www.phdeconomics.sssup.it/documents/Lesson19.pdf

Suggestions from the slides
+ HW: pp. 321-323 (cointegration)
+ Unit roots: http://faculty.washington.edu/ezivot/econ584/notes/unitroot.pdf
+ Cointegration: notes I & notes II: Where notes I = http://www2.hawaii.edu/%7Ebonham/664/materials/New_Lectures3.pdf, notes II is not to be found


## Unit Roots

Recall from section \@ref(TSComponents), TS consist of four elements: T,S,C,I. 

T,S and C are what is called determistic components. Where the rest, I, is irregular, although this might contain some properties as well. These properties are called *stochastic or random properties*

*Definition on stochastic: having a random probability distribution or pattern that may be analyzed statistically but may not be predicted precisely.*

In this chapter, we explore how a time-series that visually does not reflect nonstationary data, can in fact be non stationary.

One may observe, that even though the irregular component is often random (being stationary), it may have show nonstationarity.

In general, one can do unit root tests, to test if the data is stationary or non stationary. In general, it can be said:

    Unit Root = Non stationarity in the data

The following will explore how **Augmented Dickey-Fuller test (ADF)** can make an assessment of unit roots.


### Augmented Dickey-Fuller (ADF) test

See the equation for the ADF in the slides from L11.





## Cointegration


To check if both series (y and x) are nonstationary and the regression between these are non stationary. Then we can predict based on 

One can also say, that series are cointegrated if they move with each other, e.g., have the same trend. See the following link with an example: https://www.wallstreetmojo.com/cointegration/.
