
# Methods and Performance Measurement {#Methods}

## Forecasting Methods {#ForecastMethods}

**Naive forecasts**

*This is merely the current period is assumed to be the best predictor for the future, hence it can be written as:*

\begin{equation} 
\hat{Y}_{t+1}=Y_t
(\#eq:NaiveForecast)
\end{equation}

where, $Y_t$ = the last period, hence $\hat{Y}_{t+1}$ = the following period.

Therefore, the error can merely be written as: $e_t=Y_{t+1}-\hat{Y}_{t+1}$, being the actual amount compared with the foretasted value.

One can make several iterations to account for trending, the growth rate, or seasonal data. Those being:

+ $\hat{Y}_{t+1}=Y_t+(Y_t-Y_{t-1})$, to account for trending data (non stationary data)
+ $\hat{Y}_{t+1}=Y_t * \frac{Y_t}{Y_{t-1}}$, to account for the growth rate, notice that it only assess the growth rate to the prior period.
+ $\hat{Y}_{t+1}=Y_{t-3}+\frac{Y_t-Y_{t-4}}{4}$, to account for  quarterly trending data, the periods can naturally be changed by changing the formula, e.g. to 12. ***but notice, that this is just replicating previous periods, hence also previous seasons***

### Using Averages

We have the following:

1. Simple averages, which merely takes the average of all observations.
2. Moving averages, which account for the given time frame. This can be extended by,
3. Double moving averages, often seen when you need the center value of a period consisting of an even number of periods, where there is no actual median value, thus one can extend the MA with a double MA.

#### Simple Averages

*One may assume that it is sufficient to apply the average of all observations, to predict the next period, hence we can say:*

\begin{equation} 
\hat{Y}_{t+1}=\frac{1}{n}\sum^t_{i=1}Y_i
(\#eq:SimpleAverages)
\end{equation} 


This is appropriate if the data has shown historical stability, thus without seasons, trends and etc.

#### Moving Average (MA) {#MA}

*One may apply a moving average instead, accounting for k periods, also one could extend this by adding weights. For practical purposes only a k period MA is show:*

\begin{equation}
\hat{Y}_{t+1}=\frac{Y_t+Y_{t-1}+...+Y_{t-k}}{k}
(\#eq:MA)
\end{equation}

*this may be applied to remove seasonal effect, either by k=4 or 12 if the data is respectively quarterly or monthly*

#### Double Moving Average

*This is simply doing moving averages twice, hence it is an extension of equation \@ref(eq:MA)*

As mentioned, often seen when one wants the median when using an even number of periods, e.g. 12 months, hence double MA can be applied.

\begin{equation}
M_t=\hat{Y}_{t+1}=\frac{Y_t+Y_{t-1}+...+Y_{t-k+1}}{k}
(\#eq:DMA)
\end{equation}

\begin{equation}
M'_t=\frac{M_t+M_{t-1}+...+M_{t-k+1}}{k}
(\#eq:DMA2)
\end{equation}

\begin{equation}
a_t=M_t+\left(M_t-M_t\right)
\end{equation}

\begin{equation}
b_t=\frac{2}{k-1}\left(M_t-M'_t\right)
\end{equation}

Thence we are able to say:

\begin{equation}
\hat{Y}_{t+p}=a_t+b_t*p
(\#eq:DMAPPeriods)
\end{equation}


### Linear regressions

+ Linear regression with a trend: that is normal linear regression, where the trend is added as a counter, which will account for the trend, given it is linear.

### Non linear regressions

+ Non linear regression with trend
+ Causal regression

### Smoothing methods

#### Exponential smoothing

*This is exponentially weighted moving average of all historical values, meaning that the most recent value will be assigned the most weight. Hence we merely add different weights to past periods, thus there is no specific way to adjust for trend and seasonality, which is a limitation of exponential smoothing, it can be written as:*

\begin{equation}
\hat{Y}_{t+1}=\alpha Y_t+\left(1-\alpha\right)\hat{Y}_t
\end{equation}
thus:
\begin{equation}
=\hat{Y}_t+\alpha(Y_t-\hat{Y}_t)
\end{equation}

Where $\alpha$ = the smoothing constant, thus is can be between 0 and 1. The higher alpha the largest weight to the most recent observation.

**Then how to choose the smoothing parameter $\alpha$?**

+ For stable predictions, choose a high alpha
+ For sensitive predictions, choose low alpha
+ Test different alpha values and compare the models using the performance measures in section \@ref(PerformanceMeasurements).

#### Holt's exponential smoothing, **Put words to this**
#### Winters' exponential smoothing, **Put words to this**
#### Moving Averages, see section \@ref(MA)


### ARIMA

*Decomposition of the time series*

+ AR:
+ MA:
+ ARMA:
+ ARIMA:

\

## Performance Measurements {#PerformanceMeasurements}

+ Mean error (ME): 

\begin{equation}
ME=\frac{1}{n}\sum_{ }^{ }\left(Y_t-\hat{Y}_t\right)$
(\#eq:ME)
\end{equation} 

+ Mean Absolute Deviation (error): 

\begin{equation}
MAD\left(i.e.\ MAE\right)\ =\ \frac{1}{n}\cdot\sum_{ }^{ }\left|Y_t-\hat{Y}_t\right|
(\#eq:MAD)
\end{equation} 

+ Mean Percentage Error (MPE): 

\begin{equation}
MPE\ =\ \frac{1}{n}\ \sum_{ }^{ }\frac{\left(Y_t-\hat{Y}_t\right)}{Y_t}
(\#eq:MPE)
\end{equation} 

+ Mean Absolute Percentage Error (MAPE): 

\begin{equation}
MAPE\ =\ \frac{1}{n}\ \sum_{ }^{ }\frac{|\left(Y_t-\hat{Y}_t\right)|}{|Y_t|}
(\#eq:MAPE)
\end{equation} 

+ Mean-Squared Error (MSE): 

\begin{equation}
MSE=\frac{1}{n}\sum_{ }^{ }(Y_t-\hat{Y}_t)^2
(\#eq:MSE)
\end{equation}

+ Root Mean-Squared Error: 

\begin{equation}
RMSE=\sqrt{MSE}
(\#eq:MSE)
\end{equation}










