<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.1 Simple Linear Regression | Business Forecasting</title>
  <meta name="description" content="5.1 Simple Linear Regression | Business Forecasting" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="5.1 Simple Linear Regression | Business Forecasting" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.1 Simple Linear Regression | Business Forecasting" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="simple-and-multiple-linear-regression.html"/>
<link rel="next" href="multiple-linear-regression.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>setup</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="curriculum.html"><a href="curriculum.html"><i class="fa fa-check"></i><b>2</b> Curriculum</a></li>
<li class="chapter" data-level="3" data-path="qualitative-forecasting-methods.html"><a href="qualitative-forecasting-methods.html"><i class="fa fa-check"></i><b>3</b> Qualitative Forecasting Methods</a>
<ul>
<li class="chapter" data-level="3.1" data-path="judgmental-forecasting-and-forecast-adjustments.html"><a href="judgmental-forecasting-and-forecast-adjustments.html"><i class="fa fa-check"></i><b>3.1</b> Judgmental Forecasting and Forecast Adjustments</a></li>
<li class="chapter" data-level="3.2" data-path="articles.html"><a href="articles.html"><i class="fa fa-check"></i><b>3.2</b> Articles</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="articles.html"><a href="articles.html#a-new-product-growth-model-for-consumer-durables-management-science"><i class="fa fa-check"></i><b>3.2.1</b> A new product growth model for consumer durables,” Management Science</a></li>
<li class="chapter" data-level="3.2.2" data-path="articles.html"><a href="articles.html#sales-forecasts-for-existing-consumer-products"><i class="fa fa-check"></i><b>3.2.2</b> Sales Forecasts for Existing Consumer Products</a></li>
<li class="chapter" data-level="3.2.3" data-path="articles.html"><a href="articles.html#judgmental-forecasting-a-review-of-progress-over-the-last-25-years-international-journal-of-forecasting"><i class="fa fa-check"></i><b>3.2.3</b> Judgmental forecasting A review of progress over the last 25 years, International Journal of Forecasting</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="exploring-patterns-and-forecasting-techniques.html"><a href="exploring-patterns-and-forecasting-techniques.html"><i class="fa fa-check"></i><b>4</b> Exploring Patterns and Forecasting Techniques</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-forecasting-process.html"><a href="the-forecasting-process.html"><i class="fa fa-check"></i><b>4.1</b> The forecasting process</a></li>
<li class="chapter" data-level="4.2" data-path="data-patterns-and-terminology.html"><a href="data-patterns-and-terminology.html"><i class="fa fa-check"></i><b>4.2</b> Data Patterns and terminology</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="data-patterns-and-terminology.html"><a href="data-patterns-and-terminology.html#terminology"><i class="fa fa-check"></i><b>4.2.1</b> Terminology</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="DataPatternsAndModelSelection.html"><a href="DataPatternsAndModelSelection.html"><i class="fa fa-check"></i><b>4.3</b> Data Patterns and Model Selection</a></li>
<li class="chapter" data-level="4.4" data-path="exercises.html"><a href="exercises.html"><i class="fa fa-check"></i><b>4.4</b> Exercises</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="exercises.html"><a href="exercises.html#p.-92-hw-problem-8"><i class="fa fa-check"></i><b>4.4.1</b> p. 92 HW Problem 8</a></li>
<li class="chapter" data-level="4.4.2" data-path="exercises.html"><a href="exercises.html#p.-93-hw-problem-9-10"><i class="fa fa-check"></i><b>4.4.2</b> p. 93 HW Problem 9-10</a></li>
<li class="chapter" data-level="4.4.3" data-path="exercises.html"><a href="exercises.html#co2-and-sales-data"><i class="fa fa-check"></i><b>4.4.3</b> CO2 and Sales Data</a></li>
<li class="chapter" data-level="4.4.4" data-path="exercises.html"><a href="exercises.html#case-6-oo.-108-111-hw"><i class="fa fa-check"></i><b>4.4.4</b> Case 6 oo. 108-111 HW</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="simple-and-multiple-linear-regression.html"><a href="simple-and-multiple-linear-regression.html"><i class="fa fa-check"></i><b>5</b> Simple and Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>5.1</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#assumptions"><i class="fa fa-check"></i><b>5.1.1</b> Assumptions</a></li>
<li class="chapter" data-level="5.1.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#forecasting-with-a-linear-trend"><i class="fa fa-check"></i><b>5.1.2</b> Forecasting with a linear trend</a></li>
<li class="chapter" data-level="5.1.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#exercises-1"><i class="fa fa-check"></i><b>5.1.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>5.2</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#multicollinearity"><i class="fa fa-check"></i><b>5.2.1</b> Multicollinearity</a></li>
<li class="chapter" data-level="5.2.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#serial-correlation-and-omitted-variables"><i class="fa fa-check"></i><b>5.2.2</b> Serial correlation and omitted variables</a></li>
<li class="chapter" data-level="5.2.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#selection-criteria"><i class="fa fa-check"></i><b>5.2.3</b> Selection criteria</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="time-series-decomposition-and-regression-with-time-series-data.html"><a href="time-series-decomposition-and-regression-with-time-series-data.html"><i class="fa fa-check"></i><b>6</b> Time-Series Decomposition and Regression with Time-Series Data</a>
<ul>
<li class="chapter" data-level="6.1" data-path="TSComponents.html"><a href="TSComponents.html"><i class="fa fa-check"></i><b>6.1</b> Time Series and Their Components (HW)</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="TSComponents.html"><a href="TSComponents.html#additional-on-trend"><i class="fa fa-check"></i><b>6.1.1</b> Additional on trend</a></li>
<li class="chapter" data-level="6.1.2" data-path="TSComponents.html"><a href="TSComponents.html#additional-on-seasonal-pattern"><i class="fa fa-check"></i><b>6.1.2</b> Additional on seasonal pattern</a></li>
<li class="chapter" data-level="6.1.3" data-path="TSComponents.html"><a href="TSComponents.html#cyclical-and-irregular-variations"><i class="fa fa-check"></i><b>6.1.3</b> Cyclical and Irregular Variations</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="methods-of-decomposing.html"><a href="methods-of-decomposing.html"><i class="fa fa-check"></i><b>6.2</b> Methods of decomposing</a></li>
<li class="chapter" data-level="6.3" data-path="regression-with-time-series-data.html"><a href="regression-with-time-series-data.html"><i class="fa fa-check"></i><b>6.3</b> Regression with time series data</a></li>
<li class="chapter" data-level="6.4" data-path="the-success-criteria-and-process.html"><a href="the-success-criteria-and-process.html"><i class="fa fa-check"></i><b>6.4</b> The success criteria and process</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="the-success-criteria-and-process.html"><a href="the-success-criteria-and-process.html#success-criteria"><i class="fa fa-check"></i><b>6.4.1</b> Success Criteria</a></li>
<li class="chapter" data-level="6.4.2" data-path="the-success-criteria-and-process.html"><a href="the-success-criteria-and-process.html#DecomposingWithMA"><i class="fa fa-check"></i><b>6.4.2</b> The Process</a></li>
<li class="chapter" data-level="6.4.3" data-path="the-success-criteria-and-process.html"><a href="the-success-criteria-and-process.html#Autocorellation"><i class="fa fa-check"></i><b>6.4.3</b> Autocorellation</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="exercises-2.html"><a href="exercises-2.html"><i class="fa fa-check"></i><b>6.5</b> Exercises</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="exercises-2.html"><a href="exercises-2.html#alomega-food-stores-case-6-p.-166-case-7-p.-348"><i class="fa fa-check"></i><b>6.5.1</b> Alomega Food Stores, case 6 p. 166 + case 7 p. 348</a></li>
<li class="chapter" data-level="6.5.2" data-path="exercises-2.html"><a href="exercises-2.html#ex:MonthlySalesData"><i class="fa fa-check"></i><b>6.5.2</b> Monthly Sales Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ARIMA.html"><a href="ARIMA.html"><i class="fa fa-check"></i><b>7</b> ARIMA Models + ADL and Box-Jenkins Methodology</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ARIMAΗ2.html"><a href="ARIMAΗ2.html"><i class="fa fa-check"></i><b>7.1</b> ARIMA</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="ARIMAΗ2.html"><a href="ARIMAΗ2.html#elaborating-on-ar-models"><i class="fa fa-check"></i><b>7.1.1</b> Elaborating on AR models</a></li>
<li class="chapter" data-level="7.1.2" data-path="ARIMAΗ2.html"><a href="ARIMAΗ2.html#elaborating-on-ma-models"><i class="fa fa-check"></i><b>7.1.2</b> Elaborating on MA models</a></li>
<li class="chapter" data-level="7.1.3" data-path="ARIMAΗ2.html"><a href="ARIMAΗ2.html#elaborating-on-integration-models"><i class="fa fa-check"></i><b>7.1.3</b> Elaborating on Integration models</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="model-building-process.html"><a href="model-building-process.html"><i class="fa fa-check"></i><b>7.2</b> Model Building Process</a></li>
<li class="chapter" data-level="7.3" data-path="advantages-and-disadvantages-for-arima-models.html"><a href="advantages-and-disadvantages-for-arima-models.html"><i class="fa fa-check"></i><b>7.3</b> Advantages and disadvantages for ARIMA models</a></li>
<li class="chapter" data-level="7.4" data-path="adl.html"><a href="adl.html"><i class="fa fa-check"></i><b>7.4</b> ADL</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="adl.html"><a href="adl.html#vector-autoregressive-var"><i class="fa fa-check"></i><b>7.4.1</b> Vector autoregressive (VAR)</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="exercises-arima.html"><a href="exercises-arima.html"><i class="fa fa-check"></i><b>7.5</b> Exercises - ARIMA</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="exercises-arima.html"><a href="exercises-arima.html#ibm-stock-problem-12-p-405"><i class="fa fa-check"></i><b>7.5.1</b> IBM stock, problem 12 p 405</a></li>
<li class="chapter" data-level="7.5.2" data-path="exercises-arima.html"><a href="exercises-arima.html#demand-data-problem-7-p-403"><i class="fa fa-check"></i><b>7.5.2</b> Demand data, problem 7 p 403</a></li>
<li class="chapter" data-level="7.5.3" data-path="exercises-arima.html"><a href="exercises-arima.html#closing-stock-quotations-problem-13-p-409"><i class="fa fa-check"></i><b>7.5.3</b> Closing stock quotations, problem 13 p 409</a></li>
<li class="chapter" data-level="7.5.4" data-path="exercises-arima.html"><a href="exercises-arima.html#hw-case-1-page-413-414-q1-3"><i class="fa fa-check"></i><b>7.5.4</b> HW: Case 1 page 413-414 (q1-3)</a></li>
<li class="chapter" data-level="7.5.5" data-path="exercises-arima.html"><a href="exercises-arima.html#hw-case-4-page-417-419"><i class="fa fa-check"></i><b>7.5.5</b> HW: Case 4 page 417-419</a></li>
<li class="chapter" data-level="7.5.6" data-path="exercises-arima.html"><a href="exercises-arima.html#sales-data-seasonal"><i class="fa fa-check"></i><b>7.5.6</b> Sales data seasonal</a></li>
<li class="chapter" data-level="7.5.7" data-path="exercises-arima.html"><a href="exercises-arima.html#in-class-assignment"><i class="fa fa-check"></i><b>7.5.7</b> In class assignment</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="exercises-adl.html"><a href="exercises-adl.html"><i class="fa fa-check"></i><b>7.6</b> Exercises - ADL</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="exercises-adl.html"><a href="exercises-adl.html#gdp-and-co2-levels"><i class="fa fa-check"></i><b>7.6.1</b> GDP and CO2 levels</a></li>
<li class="chapter" data-level="7.6.2" data-path="exercises-adl.html"><a href="exercises-adl.html#short--and-long-term-interest-rates-exchange-rates"><i class="fa fa-check"></i><b>7.6.2</b> Short- and long-term interest rates, exchange rates</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="non-stationary-time-series.html"><a href="non-stationary-time-series.html"><i class="fa fa-check"></i><b>8</b> Non Stationary Time-series</a>
<ul>
<li class="chapter" data-level="8.1" data-path="unit-roots.html"><a href="unit-roots.html"><i class="fa fa-check"></i><b>8.1</b> Unit Roots</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="unit-roots.html"><a href="unit-roots.html#augmented-dickey-fuller-adf-test"><i class="fa fa-check"></i><b>8.1.1</b> Augmented Dickey-Fuller (ADF) test</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="spurious-regression.html"><a href="spurious-regression.html"><i class="fa fa-check"></i><b>8.2</b> Spurious Regression</a></li>
<li class="chapter" data-level="8.3" data-path="cointegration.html"><a href="cointegration.html"><i class="fa fa-check"></i><b>8.3</b> Cointegration</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="cointegration.html"><a href="cointegration.html#checking-for-cointegration"><i class="fa fa-check"></i><b>8.3.1</b> Checking for cointegration</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="exercises-3.html"><a href="exercises-3.html"><i class="fa fa-check"></i><b>8.4</b> Exercises</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="exercises-3.html"><a href="exercises-3.html#DairyData"><i class="fa fa-check"></i><b>8.4.1</b> Dairy Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="combining-forecast-result-and-forecast-evaluation.html"><a href="combining-forecast-result-and-forecast-evaluation.html"><i class="fa fa-check"></i><b>9</b> Combining Forecast Result and Forecast Evaluation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="why-when-and-how-to-combine-forecasts.html"><a href="why-when-and-how-to-combine-forecasts.html"><i class="fa fa-check"></i><b>9.1</b> Why, when and how to combine forecasts</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="why-when-and-how-to-combine-forecasts.html"><a href="why-when-and-how-to-combine-forecasts.html#why-do-we-combine-forecasts"><i class="fa fa-check"></i><b>9.1.1</b> Why do we combine forecasts?</a></li>
<li class="chapter" data-level="9.1.2" data-path="why-when-and-how-to-combine-forecasts.html"><a href="why-when-and-how-to-combine-forecasts.html#when-to-combine-forecasts"><i class="fa fa-check"></i><b>9.1.2</b> When to combine forecasts?</a></li>
<li class="chapter" data-level="9.1.3" data-path="why-when-and-how-to-combine-forecasts.html"><a href="why-when-and-how-to-combine-forecasts.html#how-to-combine-forecasts"><i class="fa fa-check"></i><b>9.1.3</b> How to combine forecasts?</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="exercises-4.html"><a href="exercises-4.html"><i class="fa fa-check"></i><b>9.2</b> Exercises</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="exercises-4.html"><a href="exercises-4.html#air-passengers"><i class="fa fa-check"></i><b>9.2.1</b> Air passengers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="exam-cases.html"><a href="exam-cases.html"><i class="fa fa-check"></i><b>10</b> Exam cases</a>
<ul>
<li class="chapter" data-level="10.1" data-path="exam-2018.html"><a href="exam-2018.html"><i class="fa fa-check"></i><b>10.1</b> Exam 2018</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="exam-2018.html"><a href="exam-2018.html#case-1"><i class="fa fa-check"></i><b>10.1.1</b> Case 1</a></li>
<li class="chapter" data-level="10.1.2" data-path="exam-2018.html"><a href="exam-2018.html#q3"><i class="fa fa-check"></i><b>10.1.2</b> Q3</a></li>
<li class="chapter" data-level="10.1.3" data-path="exam-2018.html"><a href="exam-2018.html#q4"><i class="fa fa-check"></i><b>10.1.3</b> Q4</a></li>
<li class="chapter" data-level="10.1.4" data-path="exam-2018.html"><a href="exam-2018.html#q5"><i class="fa fa-check"></i><b>10.1.4</b> Q5</a></li>
<li class="chapter" data-level="10.1.5" data-path="exam-2018.html"><a href="exam-2018.html#q6"><i class="fa fa-check"></i><b>10.1.5</b> Q6</a></li>
<li class="chapter" data-level="10.1.6" data-path="exam-2018.html"><a href="exam-2018.html#q7"><i class="fa fa-check"></i><b>10.1.6</b> Q7</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="case-2.html"><a href="case-2.html"><i class="fa fa-check"></i><b>10.2</b> Case 2</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="case-2.html"><a href="case-2.html#q1-1"><i class="fa fa-check"></i><b>10.2.1</b> Q1</a></li>
<li class="chapter" data-level="10.2.2" data-path="case-2.html"><a href="case-2.html#q2-1"><i class="fa fa-check"></i><b>10.2.2</b> Q2</a></li>
<li class="chapter" data-level="10.2.3" data-path="case-2.html"><a href="case-2.html#q3-1"><i class="fa fa-check"></i><b>10.2.3</b> Q3</a></li>
<li class="chapter" data-level="10.2.4" data-path="case-2.html"><a href="case-2.html#q4-1"><i class="fa fa-check"></i><b>10.2.4</b> Q4</a></li>
<li class="chapter" data-level="10.2.5" data-path="case-2.html"><a href="case-2.html#q5-1"><i class="fa fa-check"></i><b>10.2.5</b> Q5</a></li>
<li class="chapter" data-level="10.2.6" data-path="case-2.html"><a href="case-2.html#q6-1"><i class="fa fa-check"></i><b>10.2.6</b> Q6</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="communicating-technical-findings.html"><a href="communicating-technical-findings.html"><i class="fa fa-check"></i><b>11</b> Communicating Technical Findings</a></li>
<li class="chapter" data-level="12" data-path="Methods.html"><a href="Methods.html"><i class="fa fa-check"></i><b>12</b> Methods and Performance Measurement</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ForecastMethods.html"><a href="ForecastMethods.html"><i class="fa fa-check"></i><b>12.1</b> Forecasting Methods</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="ForecastMethods.html"><a href="ForecastMethods.html#using-averages"><i class="fa fa-check"></i><b>12.1.1</b> Using Averages</a></li>
<li class="chapter" data-level="12.1.2" data-path="ForecastMethods.html"><a href="ForecastMethods.html#linear-regressions"><i class="fa fa-check"></i><b>12.1.2</b> Linear regressions</a></li>
<li class="chapter" data-level="12.1.3" data-path="ForecastMethods.html"><a href="ForecastMethods.html#non-linear-regressions"><i class="fa fa-check"></i><b>12.1.3</b> Non linear regressions</a></li>
<li class="chapter" data-level="12.1.4" data-path="ForecastMethods.html"><a href="ForecastMethods.html#smoothing-methods"><i class="fa fa-check"></i><b>12.1.4</b> Smoothing methods</a></li>
<li class="chapter" data-level="12.1.5" data-path="ForecastMethods.html"><a href="ForecastMethods.html#arima"><i class="fa fa-check"></i><b>12.1.5</b> ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="PerformanceMeasurements.html"><a href="PerformanceMeasurements.html"><i class="fa fa-check"></i><b>12.2</b> Performance Measurements</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="PerformanceMeasurements.html"><a href="PerformanceMeasurements.html#error-terms"><i class="fa fa-check"></i><b>12.2.1</b> Error terms</a></li>
<li class="chapter" data-level="12.2.2" data-path="PerformanceMeasurements.html"><a href="PerformanceMeasurements.html#multicollinearity-1"><i class="fa fa-check"></i><b>12.2.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="formulas.html"><a href="formulas.html"><i class="fa fa-check"></i><b>12.3</b> Formulas</a></li>
<li class="chapter" data-level="12.4" data-path="loops.html"><a href="loops.html"><i class="fa fa-check"></i><b>12.4</b> Loops!!!!</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="loops.html"><a href="loops.html#holtwinters-smoothing---finding-optimal-frequency"><i class="fa fa-check"></i><b>12.4.1</b> HoltWinters Smoothing - finding optimal frequency</a></li>
<li class="chapter" data-level="12.4.2" data-path="loops.html"><a href="loops.html#arima---it-is-not-really-that-useful-does-not-have-all-combinations"><i class="fa fa-check"></i><b>12.4.2</b> ARIMA - it is not really that useful, does not have all combinations</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Business Forecasting</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-linear-regression" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Simple Linear Regression</h2>
<p>I will not go much in details with what simple linaer regression is.</p>
<p>One can calculate the beta values by the following</p>
<p><span class="math display" id="eq:b0">\[\begin{equation}
b_0=\ \overline{Y}-\ b_1\overline{X}
\tag{5.1}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:b1">\[\begin{equation}
b_1=\frac{\sum_{ }^{ }\left(X-\overline{X}\right)\left(Y-\overline{Y}\right)}{\sum_{ }^{ }\left(X-\overline{X}\right)^{^2}}
\tag{5.2}
\end{equation}\]</span></p>
<p>Where point forecast, hence <span class="math inline">\(\hat{Y}\)</span> is merely the sum of the linear equation, hence <span class="math inline">\(\hat{Y}=b_0+b_1X^*\)</span>, where <span class="math inline">\(X^*\)</span> is the specific X values. Thence one can estimate the standard error by:</p>
<p><span class="math display" id="eq:SELinear">\[\begin{equation}
s_{yx}=\sqrt{\frac{\sum_{ }^{ }\left(Y-\overline{Y}\right)^{^2}}{n-2}}
\tag{5.3}
\end{equation}\]</span></p>
<p><em>Equations <a href="simple-linear-regression.html#eq:SELinear">(5.3)</a> can also be written otherwise, see the slides for that.</em></p>
<p><strong>The residuals can be broken down to the following</strong></p>
<p><span class="math display" id="eq:error">\[\begin{equation}
\sum_{ }^{ }\left(Y-\overline{Y}\right)^{^2}=\sum_{ }^{ }\left(\hat{Y}-\ \overline{Y}\right)^{^2}+\sum_{ }^{ }\left(Y-\ \hat{Y}\right)^{^2}
\tag{5.4}
\end{equation}\]</span></p>
<p>Which consist of the following three elements.</p>
<p><span class="math display" id="eq:error2">\[\begin{equation}
SST = SSR + SSE
\tag{5.5}
\end{equation}\]</span></p>
<p>The residuals can then be applied for a goodness of fit assessment, where one can identify R squared-</p>
<p><span class="math display" id="eq:error2">\[\begin{equation}
R^2=\frac{SSR}{SST}
\tag{5.5}
\end{equation}\]</span></p>
<p><strong><em>So what can the linear regression then be used for?</em></strong></p>
<ol style="list-style-type: decimal">
<li>Inference</li>
<li>Prediction</li>
</ol>
<p><em>Notice, that inference can only be done when the model is adequate, hence the assumptions actually being met.</em></p>
<div id="assumptions" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Assumptions</h3>
<p>We have the following assumptions for a linear model:</p>
<ol style="list-style-type: decimal">
<li>The underlying relationship between dependent and independent variable is actually linear</li>
<li>Independent residuals</li>
<li>Homoskedastic residuals (show constant variance)</li>
<li>Identically distributed (In general, normal distribution is assumed)</li>
</ol>
<p><strong>Hence how is the assumptions tested?</strong></p>
<p>Some can be done before analysis and others after the model is applied, hence it can be described by the following:</p>
<ul>
<li>Before the model is applied:
<ol style="list-style-type: decimal">
<li>The underlying relationship between dependent and independent variable is actually linear</li>
</ol></li>
<li>After the model is applied (doing diagnostics):
<ol start="2" style="list-style-type: decimal">
<li>Independent residuals</li>
<li>Homoskedastic residuals (show constant variance)</li>
<li>Identically distributed (In general, normal distribution is assumed)</li>
</ol></li>
</ul>
<p><strong>Now lets dive into the data</strong></p>
<p><strong><em>Serial correlation and Heteroskedasticity</em></strong></p>
<p><em>Notice that autocorrelation = serial correlation</em></p>
<p>Serial correlation is where the observations are trailing each other, where heteroskedasticity is where the variance is changing over timer:</p>
<div id="serial-correlation-checking-for-independent-residuals" class="section level4" number="5.1.1.1">
<h4><span class="header-section-number">5.1.1.1</span> Serial correlation (checking for independent residuals):</h4>
<p>We must make sure that the residuals does not have a clear pattern, as that means that some variables has been omitted. This can be assessed for example by:</p>
<ul>
<li>Visual inspection</li>
<li>Durbin Watson test, see equation <a href="simple-linear-regression.html#eq:DurbinWatsonTest">(5.6)</a></li>
<li>Correlogram</li>
<li>Statistical test for relationship between residuals and lagged residuals</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-20"></span>
<img src="Images/05/SerialCorrelationExample.png" alt="Serial Correlation Example" width="308" />
<p class="caption">
Figure 5.1: Serial Correlation Example
</p>
</div>
<p>Notice, that one should also test for autocorrelation in the errors, that can be done with a Durbin-Watson statistic:</p>
<p><span class="math display" id="eq:DurbinWatsonTest">\[\begin{equation}
DW\ =\frac{\sum_{ }^{ }\left(e_t-e_{t-1}\right)^{^2}}{\sum_{ }^{ }e_t^{^2}}
\tag{5.6}
\end{equation}\]</span></p>
<p>0 &lt; DW &lt; 4, where if DW = 2 it indicates no serial correlation (this is the ideal), generally if 1.5 &lt; DW &lt; 2.5 is widely used as an acceptable level.</p>
<p>If DW &gt; 2, it indicates negative serial correlation and if DW &lt; 2, it indicates that there is positive serial correlation.</p>
<p><em>One could also use correlation testing by checking correlogram of residuals or testing residuals against lagged residuals</em></p>
<p><strong>Solution</strong></p>
<ul>
<li>Try with lagging the variables</li>
</ul>
</div>
<div id="heteroskedasticity" class="section level4" number="5.1.1.2">
<h4><span class="header-section-number">5.1.1.2</span> Heteroskedasticity:</h4>
<p>We want the variance to have a constant variance. This can be checked visually, where we dont want to see a funnel shape, as in the visualization below.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-21"></span>
<img src="Images/05/HeteroskedasticityExample.png" alt="Heteroskedasticity Example" width="107" />
<p class="caption">
Figure 5.2: Heteroskedasticity Example
</p>
</div>
<p>This can also be tested with a Breusch-Pagan Test, where the null hypothesis is that all errors are equal, hence null hypothesis, is that the errors are homoskedastic.</p>
<p><strong>Solution</strong></p>
<ul>
<li>Try lagging the variables</li>
<li>Try applying differences in the observations</li>
</ul>
<p>If one observe heteroskedasticity and can’t get rid of it, then one can apply a generalized least squares method. Although this introduce a set of new assumptions.</p>
</div>
</div>
<div id="forecasting-with-a-linear-trend" class="section level3" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Forecasting with a linear trend</h3>
<p><em>If the data contain a <strong>linear</strong> trend, then we are able to make the model account for this trend.</em></p>
<p>Hence we are able to detrend the data, by including a counter as a variable.</p>
<p>Another solution may be to using the differences in the observations, e.g., using growth rates.</p>
<p><strong>This is important, as if one don’t detrend the data, then the model will merely describe the trend and not the actual values behind the trend, thus you want the model to account for the trend</strong></p>
</div>
<div id="exercises-1" class="section level3" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> Exercises</h3>
<div id="problems-5-pp.-209" class="section level4" number="5.1.3.1">
<h4><span class="header-section-number">5.1.3.1</span> Problems 5 pp. 209</h4>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="simple-linear-regression.html#cb21-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Data/Week46/prob5p209.xlsx&quot;</span>)</span>
<span id="cb21-2"><a href="simple-linear-regression.html#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> df<span class="sc">$</span>Age,<span class="at">y =</span> df<span class="sc">$</span>MaintenanceCost,) <span class="sc">+</span> <span class="fu">grid</span>(<span class="at">col =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span> <span class="fu">abline</span>(<span class="at">reg =</span> <span class="fu">lm</span>(MaintenanceCost <span class="sc">~</span> Age,<span class="at">data =</span> df))</span></code></pre></div>
<p><img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-22-1.png" width="480" style="display: block; margin: auto;" /></p>
<pre><code>## integer(0)</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="simple-linear-regression.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="at">object =</span> <span class="fu">lm</span>(MaintenanceCost <span class="sc">~</span> Age,<span class="at">data =</span> df))</span></code></pre></div>
<pre><code>## (Intercept)         Age 
##   208.20335    70.91813</code></pre>
<p><strong>If age is the dependent variable</strong>
We see that the intercept is - 1.78, indicating that if there are no maintenance costs, then the age of the vehicle is -1.78 years old, which is naturally not possible, hence we see that the linear relathionship indicates that there will always be maintenance costs.</p>
<p><strong>If maintenance cost is the dependent variable</strong>
We see that the intercept is 208, hence there will be a begin maintenance of 208, which will always be there, and then for each year, it is expected to increase with about 71.</p>
<p>We can then test to see if the relationship is significant from a statistic point of view.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="simple-linear-regression.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Age <span class="sc">~</span> .,<span class="at">data =</span> df) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Age ~ ., data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.6658 -1.0498 -0.7737  1.0125  2.0119 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     -1.789563   1.268264  -1.411 0.201098    
## MaintenanceCost  0.012398   0.001737   7.139 0.000187 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.476 on 7 degrees of freedom
## Multiple R-squared:  0.8792, Adjusted R-squared:  0.862 
## F-statistic: 50.96 on 1 and 7 DF,  p-value: 0.0001872</code></pre>
<p>We see that there is statistical evidence to say that the relationship is linear. Also the coefficient of determination is 86% hence 86 of the variance is explained by the x variable.</p>
<p>Now we can do the diagnostics:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="simple-linear-regression.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(Age <span class="sc">~</span> .,<span class="at">data =</span> df))</span></code></pre></div>
<p><img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-25-1.png" width="480" style="display: block; margin: auto;" /><img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-25-2.png" width="480" style="display: block; margin: auto;" /><img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-25-3.png" width="480" style="display: block; margin: auto;" /><img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-25-4.png" width="480" style="display: block; margin: auto;" /></p>
<ul>
<li>Before the model is applied:
<ul>
<li>The underlying relationship between dependent and independent variable is actually linear, <strong>This we must assume</strong></li>
</ul></li>
<li>After the model is applied (doing diagnostics):
<ul>
<li>Independent residuals <strong>We dont say any indication that the residuals are not independent.</strong></li>
<li>Homoskedastic residuals (show constant variance) <strong>The variance appear to be constant</strong></li>
<li>Identically distributed (In general, normal distribution is assumed) <strong>This we must assume</strong></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="simple-linear-regression.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span></code></pre></div>
</div>
<div id="problem-11-p.-212-hw" class="section level4" number="5.1.3.2">
<h4><span class="header-section-number">5.1.3.2</span> Problem 11 p. 212 HW</h4>
</div>
<div id="cases-2-hw" class="section level4" number="5.1.3.3">
<h4><span class="header-section-number">5.1.3.3</span> Cases 2 HW</h4>
<p>Notice that the X is deviations from 65 degrees, as 65 degrees is the ideal for the production, hence when one read 10 degrees, then it is in fact 75 degrees or 55. Notice that the deviation is in absolut values.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="simple-linear-regression.html#cb29-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Data/Week46/Case2p222.xlsx&quot;</span>)</span>
<span id="cb29-2"><a href="simple-linear-regression.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co">#head(df) #To see the first observations in each</span></span>
<span id="cb29-3"><a href="simple-linear-regression.html#cb29-3" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> df<span class="sc">$</span>Y</span>
<span id="cb29-4"><a href="simple-linear-regression.html#cb29-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> df<span class="sc">$</span>X</span>
<span id="cb29-5"><a href="simple-linear-regression.html#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter.smooth</span>(<span class="at">x=</span>X, <span class="at">y=</span>Y, <span class="at">main=</span><span class="st">&quot;Y ~ X&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-26"></span>
<img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-26-1.png" alt="Plotting the model" width="480" />
<p class="caption">
Figure 5.3: Plotting the model
</p>
</div>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="simple-linear-regression.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Y, X)</span></code></pre></div>
<pre><code>## [1] -0.8010968</code></pre>
<p>We see that the correlation is negative, hence -0.8</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="simple-linear-regression.html#cb32-1" aria-hidden="true" tabindex="-1"></a>linMod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X) <span class="co">#To omit intercept when necessary, the formula can be written for example as lm(cost ~ age - 1)</span></span>
<span id="cb32-2"><a href="simple-linear-regression.html#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linMod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -91.38 -43.83 -12.64  44.48 122.25 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  552.040     22.851  24.158  &lt; 2e-16 ***
## X             -8.911      1.453  -6.133 4.37e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 59.41 on 21 degrees of freedom
## Multiple R-squared:  0.6418, Adjusted R-squared:  0.6247 
## F-statistic: 37.62 on 1 and 21 DF,  p-value: 4.374e-06</code></pre>
<p>We see an R square of 62.47 indicating that the linear relationship is not describing the relationship in the sample data very well, which the illustration above also show quite well.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="simple-linear-regression.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">resid</span>(linMod))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-29"></span>
<img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-29-1.png" alt="Residuals Case 2" width="480" />
<p class="caption">
Figure 5.4: Residuals Case 2
</p>
</div>
<p>Now we can assess if the data show autocorrelation. That can be done by using the <code>acf()</code></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="simple-linear-regression.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">resid</span>(linMod)) <span class="co"># white noise residuals?</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-30"></span>
<img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-30-1.png" alt="Correlogram" width="480" />
<p class="caption">
Figure 5.5: Correlogram
</p>
</div>
<p>The data appear to show white noise, although there appear to be some pattern, which may show seasons in the data.</p>
<p>We can test to see if the residuals actually show constant variance, of the variance is not constant (heteroskedasticity)</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="simple-linear-regression.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(linMod) <span class="co"># Breusch-Pagan test H_0: variance is constant.</span></span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  linMod
## BP = 1.069, df = 1, p-value = 0.3012</code></pre>
<p>Since the p value is not significant, there is not enough evidance to reject the null hypothesis, hence we may assume that the residuals show constant variance.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="simple-linear-regression.html#cb38-1" aria-hidden="true" tabindex="-1"></a>{ <span class="fu">AIC</span>(linMod) <span class="sc">%&gt;%</span> <span class="fu">print</span>()</span>
<span id="cb38-2"><a href="simple-linear-regression.html#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">BIC</span>(linMod) <span class="sc">%&gt;%</span> <span class="fu">print</span>()}</span></code></pre></div>
<pre><code>## [1] 257.0604
## [1] 260.4669</code></pre>
<p>We see the different information criteria, but we need other models to assess what is good and what is bad.</p>
<p><strong>Q1 How many units would your forecast for a day in which the high temperatire is 80 degrees</strong></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="simple-linear-regression.html#cb40-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">X=</span><span class="dv">24</span>) <span class="co">#65+24=89 degrees</span></span>
<span id="cb40-2"><a href="simple-linear-regression.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(linMod, a) <span class="sc">%&gt;%</span> <span class="fu">print</span>()</span></code></pre></div>
<pre><code>##        1 
## 338.1778</code></pre>
<p>Hence we may expect 338 units to be produced on a day with 89 degrees.</p>
<p><strong>Q2</strong></p>
<p>When the degrees is 41, hence also a deviation of 24 degrees.</p>
<p><strong>Q3 Is the forecasting tool effective?</strong></p>
<p>We saw earlier that 80% of the variance is explained, although there is probably room for optimization</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="simple-linear-regression.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span></code></pre></div>
</div>
<div id="case-3-from-hw" class="section level4" number="5.1.3.4">
<h4><span class="header-section-number">5.1.3.4</span> Case 3 from HW</h4>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="simple-linear-regression.html#cb43-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Data/Week46/Case2p222.xlsx&quot;</span>)</span>
<span id="cb43-2"><a href="simple-linear-regression.html#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co">#head(df) #To see the first observations in each</span></span>
<span id="cb43-3"><a href="simple-linear-regression.html#cb43-3" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> df<span class="sc">$</span>Y</span>
<span id="cb43-4"><a href="simple-linear-regression.html#cb43-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> df<span class="sc">$</span>X</span>
<span id="cb43-5"><a href="simple-linear-regression.html#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X,Y)</span></code></pre></div>
<p><img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-35-1.png" width="480" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="simple-linear-regression.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Y, X)</span></code></pre></div>
<pre><code>## [1] -0.8010968</code></pre>
<p>We see that the correlation is negative, hence -0.8</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="simple-linear-regression.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(Y,X)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Y and X
## t = -6.1335, df = 21, p-value = 4.374e-06
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.9121082 -0.5806250
## sample estimates:
##        cor 
## -0.8010968</code></pre>
</div>
<div id="detrending-thorugh-regression-co2" class="section level4" number="5.1.3.5">
<h4><span class="header-section-number">5.1.3.5</span> Detrending thorugh regression: CO2</h4>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="simple-linear-regression.html#cb48-1" aria-hidden="true" tabindex="-1"></a>CO2levels <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Data/Week46/CO2levels(1).xlsx&quot;</span>)</span>
<span id="cb48-2"><a href="simple-linear-regression.html#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="simple-linear-regression.html#cb48-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">ts</span>(CO2levels, <span class="at">frequency =</span> <span class="dv">12</span>) <span class="co">#Monthly series, so we specify the frequency=12.</span></span>
<span id="cb48-4"><a href="simple-linear-regression.html#cb48-4" aria-hidden="true" tabindex="-1"></a>trend <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(y)) <span class="co">#Creating the linear trend, simply a counter</span></span>
<span id="cb48-5"><a href="simple-linear-regression.html#cb48-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-6"><a href="simple-linear-regression.html#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-37"></span>
<img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-37-1.png" alt="CO2 data" width="480" />
<p class="caption">
Figure 5.6: CO2 data
</p>
</div>
<p>We see that there is a trend and cycles. This we want to get rid of, by enabling the model to account for that.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="simple-linear-regression.html#cb49-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> trend)</span>
<span id="cb49-2"><a href="simple-linear-regression.html#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ trend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -4.392 -1.866  0.199  2.190  3.677 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 3.293e+02  3.462e-01  951.40   &lt;2e-16 ***
## trend       1.210e-01  3.707e-03   32.64   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.186 on 159 degrees of freedom
## Multiple R-squared:  0.8701, Adjusted R-squared:  0.8693 
## F-statistic:  1065 on 1 and 159 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="simple-linear-regression.html#cb51-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-2"><a href="simple-linear-regression.html#cb51-2" aria-hidden="true" tabindex="-1"></a>ystar <span class="ot">&lt;-</span> <span class="fu">resid</span>(fit) <span class="co">#ystar is the detrended series, which is simply the residuals from the previous regression.</span></span>
<span id="cb51-3"><a href="simple-linear-regression.html#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="simple-linear-regression.html#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ystar) <span class="sc">+</span> <span class="fu">lines</span>(ystar, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-38"></span>
<img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-38-1.png" alt="Detrended series" width="480" />
<p class="caption">
Figure 5.7: Detrended series
</p>
</div>
<pre><code>## integer(0)</code></pre>
<p>Now wee see that the data show constant variance and appear to be stationary around a mean of 0.</p>
<p>But did we get rid of the seasonality?</p>
<p>To compare, one can print the detrended and the initial data.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="simple-linear-regression.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb53-2"><a href="simple-linear-regression.html#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(y, <span class="dv">50</span>)</span>
<span id="cb53-3"><a href="simple-linear-regression.html#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="at">x =</span> ystar,<span class="at">lag.max =</span>  <span class="dv">50</span>) <span class="co">#We can specify how many lags we want to plot. Here I just chose 50. </span></span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-39"></span>
<img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-39-1.png" alt="Correlogram comparison detrended" width="480" />
<p class="caption">
Figure 5.8: Correlogram comparison detrended
</p>
</div>
<p>Hence we see that we got rid of the trend, but still see that there is great seasonality in the data.</p>
<p><strong>Alternative to detrending –&gt; differencing</strong></p>
<p><em>An alternative to detrending with the trend variable, is to using differencing</em></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="simple-linear-regression.html#cb54-1" aria-hidden="true" tabindex="-1"></a>dy <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="at">x =</span> y,<span class="at">lag =</span> <span class="dv">1</span>)</span>
<span id="cb54-2"><a href="simple-linear-regression.html#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dy) <span class="co">#</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-40-1"></span>
<img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-40-1.png" alt="Detrending using differencing" width="480" />
<p class="caption">
Figure 5.9: Detrending using differencing
</p>
</div>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="simple-linear-regression.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(dy, <span class="dv">50</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-40-2"></span>
<img src="Business-Forecasting-Notebook_files/figure-html/unnamed-chunk-40-2.png" alt="Detrending using differencing" width="480" />
<p class="caption">
Figure 5.10: Detrending using differencing
</p>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simple-and-multiple-linear-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-linear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
